name: get-api-token
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Install and Build
      uses: actions/setup-node@v1 
    - name: Build
      run: |
        npm install
        npm build
      env:
        REACT_APP_API_TOKEN: ${{ secrets.REACT_APP_API_TOKEN }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
        BRANCH: main
        FOLDER: .
